### ISSUE TITLE
Tweetdeck Support

### ISSUE THREAD

**Issue by wave-dash** [insin/control-panel-for-twitter#341]
The extension "Better Tweetdeck" has essentially completely stopped working, and its developer understandably isn't interested in recreating it from scratch for the "new" Tweetdeck.

Would it be possible for Control Panel for Twitter to take over? It seems like new Tweetdeck shares a lot of DNA with standard desktop Twitter. I'd really like to be able to hide the "Discover More" tweets, for example.

**Comment by insin** [comment]
Many of Control Panel for Twitter's features would work on TweetDeck with just a little tweaking, but I won't be adding any TweetDeck stuff to it because TweetDeck is going to require a Twitter Blue subscription shortly, plus adding `tweetdeck.twitter.com` to the extension's host permissions will automatically disable it for ~150,000 people and re-prompt them for permissions when they install that version, even if they don't use TweetDeck or won't be able to.

I do have a user stylesheet which tidies it up a bit, including hiding "Discover more" tweets on browsers which support the CSS `:has()` pseudo-selector (i.e. not Firefox, yet):

https://gist.github.com/insin/ff6a392feccead6272f7d2a659a9227d

You can use it in a userstyle extension like [Stylus](https://github.com/openstyles/stylus#stylus)

**Comment by pikesaury** [comment]
https://github.com/kaonasi-biwa/Twitter-UI-Customizer/

It may only work in Japanese, but add-ons like this exist.
Why not use them together?
