### ISSUE TITLE
Unable to post pictures

### ISSUE THREAD

**Issue by Damrak1** [insin/control-panel-for-twitter#459]
It's not possible to load a picture in a tweet anymore in Chrome 118.0.5993.117 (Officiële build) (64-bits).

![ext1](https://github.com/insin/control-panel-for-twitter/assets/103885608/62d8c202-91ca-4035-9282-55fe865283d5)

is replaced with:

![ext2](https://github.com/insin/control-panel-for-twitter/assets/103885608/b6c551f2-66f4-46e1-9d31-588f81c1fcf1)

The first icon only lets you choose a gif.

**Comment by madamcrusher** [comment]
Hello, sorry for hijacking but I am having the same issue.
At the moment, I solved by removing the thick on "Hide the For You Timeline", the issue seems to be an overlapping.
So basically the pictures button and the gif button are overlapping each other with hiding "For you" and they are not with showing.

**Comment by Tagishsimon** [comment]
Same issie, but fwiw if I use the large tweet button to the left, the pop-up tweet UI does allow a picture to be added.

Select the large Tweet on the left:
<img width="840" alt="Screenshot 2023-10-29 at 01 24 46" src="https://github.com/insin/control-panel-for-twitter/assets/9000789/e662c4cd-22b2-49cc-9e28-6fc87b32ef62">


All good:
<img width="880" alt="Screenshot 2023-10-29 at 01 25 00" src="https://github.com/insin/control-panel-for-twitter/assets/9000789/02c94f40-a6b9-453c-b51b-e60b95e80ace">
