### ISSUE TITLE
[feature request] Re-enable Twitter Circles tweetting

### ISSUE THREAD

**Issue by LuisMayo** [insin/control-panel-for-twitter#461]
It seems Backend code wasn't removed so you just need to enable `trusted_friends_tweet_creation_enabled` on the frontend Features Flags

**Comment by insin** [comment]
We're not going to add a specific feature for this because the rest of Twitter Circles is eventually going to be removed, but we could add something to the Experiments section of the extension options which will let you activate Twitter's hidden extension flags UI in the Settings section so you can do it yourself.

**Comment by shatopop** [comment]
The backend now prevents you from creating new Circle tweets and I doubt they are reverting it because of.. well, obvious reasons

![image](https://github.com/insin/control-panel-for-twitter/assets/37744843/7b1ea5d0-a63c-45bf-a043-588f604dd247)

**Comment by LuisMayo** [comment]
Sad
