### ISSUE TITLE
'Who to follow' showing up again

### ISSUE THREAD

**Issue by deusexcalamus** [insin/control-panel-for-twitter#561]
![image](https://github.com/insin/control-panel-for-twitter/assets/8674645/1ba5147e-c932-40d4-86be-19dac0532a5e)
seen here: https://twitter.com/DiscussingFilm

**Comment by insin** [comment]
This is still working for me, so it's probably the same cause as #559, which was also likely caused by Control Panel failing to run on profile pages after recent Twitter changes - still looking into these

![Screenshot 2024-05-14 at 1 39 09 PM](https://github.com/insin/control-panel-for-twitter/assets/226692/ee46b9f3-9bc1-4d7b-8070-75359d17862a)

![Screenshot 2024-05-14 at 1 39 24 PM](https://github.com/insin/control-panel-for-twitter/assets/226692/4494e479-ea68-47e1-b442-a331faf9b922)

**Comment by boilinabag** [comment]
using the new update. still getting who to follow, though i toggle on the ext. and it goes away. no biggie. would like a way to force them not adding users i dont follow, though the algo thinks i would want to see it. 

brave, ublock, ghostery, vpn.
